### ISSUE TITLE
Error: Failed attempt to create a corpus

### ISSUE THREAD

**Issue by bcarrmichael** [voyanttools/Voyant#16]
A pre-existing corpus is now returning an error upon loading:

![Screen Shot 2022-04-12 at 12 16 30 pm](https://user-images.githubusercontent.com/89497628/162865859-b57ee325-9d6a-45b3-982e-4cbc5eed8ef7.png)

```A corpus was specified but does not exist, could not be migrated and could not be recreated: ee7f3b1fb2a0a8702bf247afa8ae72a1
java.lang.IllegalArgumentException: A corpus was specified but does not exist, could not be migrated and could not be recreated: ee7f3b1fb2a0a8702bf247afa8ae72a1
	at org.voyanttools.trombone.tool.corpus.CorpusManager.run(CorpusManager.java:98)
	at org.voyanttools.trombone.tool.corpus.CorpusManager.getCorpus(CorpusManager.java:112)
	at org.voyanttools.trombone.tool.corpus.AbstractCorpusTool.run(AbstractCorpusTool.java:57)
	at org.voyanttools.trombone.tool.util.ToolRunner.run(ToolRunner.java:134)
	at org.voyanttools.trombone.Controller.run(Controller.java:110)
	at org.voyanttools.voyant.Trombone.runTromboneController(Trombone.java:337)
	at org.voyanttools.voyant.Trombone.doRequest(Trombone.java:311)
	at org.voyanttools.voyant.Trombone.doRequest(Trombone.java:146)
	at org.voyanttools.voyant.Trombone.doPost(Trombone.java:87)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I'm not certain when this began happening, any advice about the nature of this error would be greatly appreciated.

**Comment by ajmacdonald** [comment]
Hello,
Do you recall when you created this corpus?

**Comment by bcarrmichael** [comment]
I believe it would have been created some time around December 4 2020 by a previous employee of my institution. There were dozens of other corpora made around that time, and all are showing the same error. There were likely created through [https://voyant-tools.org/](https://voyant-tools.org/), not a self-hosted instance. Do corpora created through the web interface only last a certain timeframe?

**Comment by ajmacdonald** [comment]
There are no guarantees but generally we don't remove corpora unless requested.
That said, at the end of 2021 we had to relocate voyant-tools.org to a different server and unfortunately not all of the corpora survived the transfer.
