### ISSUE TITLE
Voyant Server // locally hosted on Arch Linux // "Unable to load corpus"

### ISSUE THREAD

**Issue by kneckergit** [voyanttools/Voyant#6]
Dear Andrew,
first of all: One can not thank enough for sharing Voyant Tools with the public. This is an extraordinary achievement!
Unfortunately, I was unable to get the Voyant Server running on my local machine in Linux - it does work fine in Windows though!

My system is Arch Linux with OpenJDK / JRE 16. The Voyant Server application starts just fine and opens the browser (FF, current stable). But when trying to upload or manually enter I receive an error: "Unable to load corpus. HTTP ERROR 500"

Detailed information:
`HTTP ERROR 500`
`Problem accessing /trombone. Reason:`
`Server ErrorCaused by:java.lang.IllegalAccessError: class org.voyanttools.voyant.FlexibleParametersFactory (in unnamed module @0x4e577922) cannot access class sun.security.action.GetPropertyAction (in module java.base) because module java.base does not export sun.security.action to unnamed module @0x4e577922`
	`at org.voyanttools.voyant.FlexibleParametersFactory.getstance(FlexibleParametersFactory.java:79)
	at org.voyanttools.voyant.FlexibleParametersFactory.getstance(FlexibleParametersFactory.java:51)
	at org.voyanttools.voyant.Trombone.getFlexibleParameters(Trombone.java:175)
	at org.voyanttools.voyant.Trombone.doRequest(Trombone.java:100)
	at org.voyanttools.voyant.Trombone.doPost(Trombone.java:87)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.Fillterest.fillable(Fillterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.base/java.lang.Thread.run(Thread.java:831)`

`Powered by Jetty:// 9.3.z-SNAPSHOT`

Is this a known issue? Am I doing sth. wrong?

**Comment by ajmacdonald** [comment]
I believe this is an issue with newer / non-Sun distributions of Java.
I've fixed it here: https://github.com/voyanttools/Voyant/commit/8b0305ad369a6c1c75b7981c335c8ad7cb4a8be1

**Comment by kneckergit** [comment]
Ok great, I am not tech-savvy enough to compile and test it myself. Will wait for the next release of voyant server then.
